<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Integration Test all API</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>73c2d970-6268-4c81-9ac1-dd8a30318d29</testSuiteGuid>
   <testCaseLink>
      <guid>080e1aa8-870f-4e0c-a6e6-1db112c176bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_04 Create Category</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a507e7f-10f8-49e4-a59e-6020edf62903</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>42b62493-6bf1-4fda-abed-b04f17aca972</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_15 Create Product</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04ddbada-088b-4896-8ca0-1781198b6baa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>455c5cad-9ae0-46a6-a38e-4b57d8575239</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2ad0400-9adb-4f05-8127-584443b8e155</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_17 Register</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06138d3c-3cc4-4676-89d1-47995151d866</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6797b93-d00c-46ed-a81e-c88493241a7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b684794-4bcc-4d8b-831b-42f1b22d1e61</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>22f0e450-8141-494d-aafb-ff5bdef843a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_27 Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad7c8f70-8b76-445a-85d8-bfe10acb67c5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7344805b-4b16-42c5-8e29-26bf633ddde2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_35 Transaction</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95412a92-fe31-4926-a1eb-4c7ebc849470</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83478fef-288a-4ab1-927a-74cc3a655810</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
